### ISSUE TITLE
能不能把百度小程序的回调地址写在配置里面,而不是不能配置,然后让百度默认去拿账号后台填写的回调地址

### ISSUE THREAD

**Issue by RayFongChan** [code-lives/Pays#14]
![image](https://user-images.githubusercontent.com/35999171/204124318-25af7055-d860-4809-b976-ca3f1b64dc24.png)
这里看到不能通过传递回调地址,这样测试环境和正式环境不太方便弄
![image](https://user-images.githubusercontent.com/35999171/204124350-07d4a466-f4d5-4815-b02d-9f7c5a0e70eb.png)
而百度的文档写着是可以由开发者手动传递的,麻烦大佬改一下,谢谢了

**Comment by code-lives** [comment]
安装5.4版本试试

**Comment by code-lives** [comment]
<img width="838" alt="image" src="https://user-images.githubusercontent.com/79346591/204137240-139dcf60-051b-4982-becd-b2bbecb2f0f5.png">

**Comment by RayFongChan** [comment]
![image](https://user-images.githubusercontent.com/35999171/204172322-918a38ab-99c8-4acf-b770-be7efac72e6b.png)
大佬,composer官方镜像好像还没发布5.4版本

**Comment by code-lives** [comment]
有了

**Comment by code-lives** [comment]
我开邮箱通知了。有留言可以及时看到。

**Comment by RayFongChan** [comment]
谢谢你,已经成功安装,应该没有问题了,后续遇到其他问题再留言,感谢感谢
