### ISSUE TITLE
快手获取openid的方法好像返回参数有误

### ISSUE THREAD

**Issue by chenbanjin** [code-lives/Pays#19]
![image](https://github.com/code-lives/Pays/assets/34847885/f45d4e3c-a9e2-4b25-aa1b-da67c5a4563d)
文档里显示这个接口应该返回
![image](https://github.com/code-lives/Pays/assets/34847885/77ed56db-93c5-4a1b-ac84-79279fe31008)

返回参数 | 类型 | 必须 | 说明
-- | -- | -- | --
session_key | string | 是 | session_key
open_id | string | 是 | 用户 open_id
result | string | 是 | 状态 1 是成功

返回这个参数。但是我打印出来。
![image](https://github.com/code-lives/Pays/assets/34847885/f6c939a5-d9ff-414d-b1d2-5848913a4259)
只返回这个。作者看看，是不是快手那儿有所修改。因为之前是可以的。感谢作者。

**Comment by code-lives** [comment]
版本号，代码贴出来

**Comment by code-lives** [comment]
哦。open_id 改成 openid

**Comment by chenbanjin** [comment]
不是，是快手的。 $codeData = \Applet\Pay\Factory::getInstance('Kuaishou')->init($config)->getOpenid($code);  这一个整个打印出来，就只有一串字符了。按理说应该整个返回这样一个数组的
![image](https://github.com/code-lives/Pays/assets/34847885/5e0831b4-95d4-4e1a-a524-d326bc4922c0)
文档中这种返回格式的。

**Comment by code-lives** [comment]
l948870149 我的微信

**Comment by code-lives** [comment]
使用 5.9版本吧

**Comment by chenbanjin** [comment]
好的，感谢作者
