### ISSUE TITLE
快手相关

### ISSUE THREAD

**Issue by chowjiawei** [code-lives/Pays#2]
使用文档 中 少了   详细 

 $payName='Kuaishou';//快手
    $pay= \Applet\Pay\Factory::getInstance($PayName)->init($config)->set("订单号","金额","描述",'openid', 'access_token')->getParam();

类目被固定为  3306  导致 无法产生预定单 需要改为用户传入

由于 我很慢 只能提issue了~ 希望可以更新

**Comment by code-lives** [comment]
稍等，我处理下

**Comment by code-lives** [comment]
compsoer remove 本地 4.0 版本 安装5.0版本  通过config 设置类目

**Comment by chowjiawei** [comment]
神速呀  牛
