### ISSUE TITLE
很多金额  文档外面写的是分  但是里面的操作都继续乘了100

### ISSUE THREAD

**Issue by chowjiawei** [code-lives/Pays#3]
很多金额  文档外面写的是分  但是里面的操作都继续除了100

比如我退款 现在只能这样子了
![image](https://user-images.githubusercontent.com/59349609/176412326-75d807a6-de74-4c36-ae3c-4f6ab7ad02f0.png)

![image](https://user-images.githubusercontent.com/59349609/176412352-32716d67-044d-4148-b05c-8d61d44b67ae.png)

字节小程序的  分账    文档是错的

然后 分账 显示成功 但是 实际是不成功的   字节那边看还是 支付成功 而不是分账中

![image](https://user-images.githubusercontent.com/59349609/176412521-f1e14365-c27a-4262-ae7d-b209c34afcd2.png)

**Comment by chowjiawei** [comment]
![image](https://user-images.githubusercontent.com/59349609/176414637-adff1470-599c-474c-b826-f0a215930622.png)


分账的 urlshi'yon使用错误 应该是用这个

**Comment by code-lives** [comment]
只能晚上修复了，现在不在家

**Comment by code-lives** [comment]
1. 我刚看了下分账请求的url 没问题的。因为我使用的是第一个。图一有三个分账，后面两个字节后续添加的我没用弄，我预计也是这周添加上。
2. 金额是没有问题的呀。单位是（分），难道你数据库 1 代表分吗？后台程序计算退款100元，自己在（100*100）=100元？
3. 还有个问题就是分账 虽然请求成功过，但是没用真正的把在途金额转入可体现金额，所以我放弃了，也是等180天自动到可体现金额。如果你成功了，可以和我说下。
4. 重新 安装5.0
<img width="968" alt="image" src="https://user-images.githubusercontent.com/79346591/176436112-32ea4a97-7477-4991-8a7b-c38a6e999c03.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/79346591/176436213-cab6e4e1-6add-409c-8662-98d929f86c53.png">

**Comment by chowjiawei** [comment]
分账 使用$settle是可以的    原本你的代码内部是 $query  是查询用的    

   现在很多数据库 都是使用分为单位呢

**Comment by chowjiawei** [comment]
![image](https://user-images.githubusercontent.com/59349609/176580110-ecee187d-8fa4-49f1-b9a3-7c7ccaf955b6.png)

这个文档是错的呢

**Comment by chowjiawei** [comment]
![image](https://user-images.githubusercontent.com/59349609/176580398-139f6702-316f-431f-bae7-1af8ccc4d533.png)

分账 返回的是这个呢

**Comment by chowjiawei** [comment]
那个 ×100的话  因为字节的文档  是以分为单位    所以  我觉得  可能让用户自己转换为分  会更妥当呢    或者 整个 包  都以 元为单位 也会更统一呢   我只是建议哈~~

还有 分账我是成功的  也变成了可提现金额   只要分账的url 用对就行拉   原来的 真的是不对的 是查询用的url呢

![image](https://user-images.githubusercontent.com/59349609/176580943-a03fbcc8-fe96-4557-a161-4055be87b0d5.png)

![image](https://user-images.githubusercontent.com/59349609/176580993-c4a9401c-975d-48a5-9ac9-0ea1da6898c1.png)

**Comment by chowjiawei** [comment]
![image](https://user-images.githubusercontent.com/59349609/176582215-670ad09c-bcc8-435a-8eba-4eda3a19e079.png)
 文档，您写的是分  呢~~  所以 我传的分  发现 里面还是 x 了100  就金额不对拉~

![image](https://user-images.githubusercontent.com/59349609/176582612-c04851cc-c1e3-4f60-b424-c0a20147e2ef.png)

**Comment by chowjiawei** [comment]
希望大大 可以把 抖音分账的url
改下哈~~要不然我就要重写拉~~ 只要把  url换成settle就ok啦~~
辛苦啦

**Comment by code-lives** [comment]
sorry 我把分账url搞错了，我顺便把快手的分账也加上，在把5.0重新发布一次

**Comment by code-lives** [comment]
修复了 可以试试

**Comment by chowjiawei** [comment]
ok啦
