### ISSUE TITLE
快手的 settle 什么时候可以支持呢

### ISSUE THREAD

**Issue by chowjiawei** [code-lives/Pays#4]
作者大大  
快手的 settle 什么时候可以支持呢

**Comment by code-lives** [comment]
下午我抽空完善下

**Comment by chowjiawei** [comment]
期待`

**Comment by code-lives** [comment]
重新安装5.0 版本。我这里是盲加的。因为我这没有订单

**Comment by code-lives** [comment]
金额都改为分了。自行乘除

**Comment by chowjiawei** [comment]
已经ok啦

如果版本号  会递增就好了  因为 如果版本号不变的话  线上大部分人可能都不会变更   本地是可以手动安装的  但是如果是 自动化脚本啥的  发现composer.json 和原来的一致的话  可能就不动啦
