### ISSUE TITLE
点赞作者~

### ISSUE THREAD

**Issue by chowjiawei** [code-lives/Pays#5]
作者做的包很好  一个人维护  文档有写复制的有些 问题 比如案例复制错了  或者 例子的变量名复制的别的地方  没有改过来   可以把包发扬光大  有空大家一起改下   这个包 让我 做小程序相关的支付和登录 变得非常方便  很nice

作者有learnku账号吗  我做了个备忘   如果作者在网站推广   一定会有更多人喜欢的

https://learnku.com/laravel/t/69143

**Comment by code-lives** [comment]
顺便发布了一篇文章
https://learnku.com/blog/code-live
