### ISSUE TITLE
抖音文档错误

### ISSUE THREAD

**Issue by chowjiawei** [code-lives/Pays#7]
![image](https://user-images.githubusercontent.com/59349609/177907549-0e230c8f-d672-4430-8c85-f60a5e8f58f3.png)

![image](https://user-images.githubusercontent.com/59349609/177907573-2f10e2f2-fc42-43b9-bc15-ceb60b1cb66e.png)

**Comment by chowjiawei** [comment]
并且 这2个code是选1  不是都必传的~

**Comment by code-lives** [comment]
5.1版本，传code, 第二个可以传 可以不传
