### ISSUE TITLE
字节支付的过期时间写错了

### ISSUE THREAD

**Issue by wujie0919** [code-lives/Pays#9]
public function set($order_no, $money, $title, $desc = '')
    {
        $this->orderParam["out_order_no"] = $order_no;
        $this->orderParam["total_amount"] = $money;
        $this->orderParam["subject"] = $title;
        $this->orderParam["body"] = $desc;
        $this->orderParam["notify_url"] = $this->notify_url;
        $this->orderParam["alid_time"] = $this->valid_time;
        $this->orderParam["app_id"] = $this->app_id;
        $data = json_encode(["sign" => $this->sign($this->orderParam)] + $this->orderParam);
        return json_decode($this->curl_post($this->payUrl, $data), true);
    }

$this->orderParam["alid_time"] = $this->valid_time;

应该是valid_time 而不是 alid_time

**Comment by code-lives** [comment]
换成5.3版本即可
